/* Generated By:JavaCC: Do not edit this line. InterpreterConstants.java */
package org.poormanscastle.studies.compilers.grammar.grammar3_1Interpreter.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InterpreterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINT = 1;
  /** RegularExpression Id. */
  int PLUS = 2;
  /** RegularExpression Id. */
  int DASH = 3;
  /** RegularExpression Id. */
  int STAR = 4;
  /** RegularExpression Id. */
  int SLASH = 5;
  /** RegularExpression Id. */
  int ASSIGN = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int ID = 11;
  /** RegularExpression Id. */
  int NUM = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"print\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "<ID>",
    "<NUM>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
