/* Generated By:JavaCC: Do not edit this line. IndexParserConstants.java */
package org.poormanscastle.studies.compilers.grammar.grammar_indices.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IndexParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 1;
  /** RegularExpression Id. */
  int LBRACKET = 2;
  /** RegularExpression Id. */
  int RBRACKET = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUM>",
    "\"[\"",
    "\"]\"",
  };

}
