/* Generated By:JavaCC: Do not edit this line. QuotedConstants.java */
package org.poormanscastle.studies.compilers.grammar.quoted.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QuotedConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TEXT = 1;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<TEXT>",
  };

}
