/* Generated By:JavaCC: Do not edit this line. MiniJavaConstants.java */
package org.poormanscastle.studies.compilers.grammar.minijava.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 1;
  /** RegularExpression Id. */
  int PUBLIC = 2;
  /** RegularExpression Id. */
  int PRIVATE = 3;
  /** RegularExpression Id. */
  int STATIC = 4;
  /** RegularExpression Id. */
  int ID = 5;
  /** RegularExpression Id. */
  int BRACE_LEFT = 6;
  /** RegularExpression Id. */
  int BRACE_RIGHT = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int LBRACKET = 10;
  /** RegularExpression Id. */
  int RBRACKET = 11;
  /** RegularExpression Id. */
  int LT = 12;
  /** RegularExpression Id. */
  int GT = 13;
  /** RegularExpression Id. */
  int DOT = 14;
  /** RegularExpression Id. */
  int SEMICOLON = 15;
  /** RegularExpression Id. */
  int COLON = 16;
  /** RegularExpression Id. */
  int DECIMAL = 17;
  /** RegularExpression Id. */
  int EQ = 18;
  /** RegularExpression Id. */
  int STAR = 19;
  /** RegularExpression Id. */
  int DASH = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"public\"",
    "\"private\"",
    "\"static\"",
    "<ID>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\">\"",
    "\".\"",
    "\";\"",
    "\":\"",
    "<DECIMAL>",
    "\"=\"",
    "\"*\"",
    "\"-\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 25>",
  };

}
