/* Generated By:JavaCC: Do not edit this line. HitClouConstants.java */
package org.poormanscastle.studies.compilers.grammar.hitclou.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HitClouConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLOUBAUSTEIN = 1;
  /** RegularExpression Id. */
  int PSEUDO_KOMMENTAR = 2;
  /** RegularExpression Id. */
  int FIXTEXT = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"#\\n\"",
    "\"#*#\"",
    "<FIXTEXT>",
    "<token of kind 4>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
