/* Generated By:JavaCC: Do not edit this line. V01AstParserConstants.java */
package org.poormanscastle.studies.compilers.grammar.grammar_v01.ast.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface V01AstParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINT = 1;
  /** RegularExpression Id. */
  int LPAREN = 2;
  /** RegularExpression Id. */
  int RPAREN = 3;
  /** RegularExpression Id. */
  int NOT = 4;
  /** RegularExpression Id. */
  int TIMES = 5;
  /** RegularExpression Id. */
  int DIV = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int LT = 9;
  /** RegularExpression Id. */
  int LTE = 10;
  /** RegularExpression Id. */
  int GT = 11;
  /** RegularExpression Id. */
  int GTE = 12;
  /** RegularExpression Id. */
  int EQ = 13;
  /** RegularExpression Id. */
  int NEQ = 14;
  /** RegularExpression Id. */
  int XOR = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int OR = 17;
  /** RegularExpression Id. */
  int LET = 18;
  /** RegularExpression Id. */
  int TYPE = 19;
  /** RegularExpression Id. */
  int BOOL = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int SEMICOLON = 22;
  /** RegularExpression Id. */
  int NUM = 23;
  /** RegularExpression Id. */
  int DEC = 24;
  /** RegularExpression Id. */
  int TEXT = 25;
  /** RegularExpression Id. */
  int ID = 26;
  /** RegularExpression Id. */
  int END_OF_SINGLE_LINE_COMMENT = 28;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT_MODE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"print\"",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"^\"",
    "\"&\"",
    "\"|\"",
    "\"=\"",
    "<TYPE>",
    "<BOOL>",
    "\",\"",
    "\";\"",
    "<NUM>",
    "<DEC>",
    "<TEXT>",
    "<ID>",
    "\"//\"",
    "<END_OF_SINGLE_LINE_COMMENT>",
    "<token of kind 29>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
