/* Generated By:JavaCC: Do not edit this line. PalindromeConstants.java */
package org.poormanscastle.studies.compilers.grammar.palindrome.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PalindromeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PAREN_L = 1;
  /** RegularExpression Id. */
  int PAREN_R = 2;
  /** RegularExpression Id. */
  int BRACKET_L = 3;
  /** RegularExpression Id. */
  int BRACKET_R = 4;
  /** RegularExpression Id. */
  int a = 5;
  /** RegularExpression Id. */
  int b = 6;
  /** RegularExpression Id. */
  int whitespace = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"a\"",
    "\"b\"",
    "<whitespace>",
  };

}
